import type { GridCell } from '../types';

// Grid: 10 rows (A-J, top to bottom) x 10 cols (1-10, left to right)
// Auto-generated by scripts/generate_grid.py from GPT vision analysis

export const gridAssignments: GridCell[] = [
  // === ROW A ===
  {
    row: 0, col: 0, id: 'A1',
    plantings: [],
    structures: [],
  },
  {
    row: 0, col: 1, id: 'A2',
    plantings: [],
    structures: [],
  },
  {
    row: 0, col: 2, id: 'A3',
    plantings: [],
    structures: [],
  },
  {
    row: 0, col: 3, id: 'A4',
    plantings: [],
    structures: [],
  },
  {
    row: 0, col: 4, id: 'A5',
    plantings: [
      { id: 'A5-1', abbreviation: 'sprinter BX', decodedSpeciesId: 'sprinter-bx', confidence: 'high', quantity: 1 },
      { id: 'A5-2', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 5 },
      { id: 'A5-3', abbreviation: 'verbena b', decodedSpeciesId: 'verbena-bonariensis', confidence: 'high', quantity: 1 },
      { id: 'A5-4', abbreviation: 'knautia macedon', decodedSpeciesId: 'knautia-macedo', confidence: 'high', quantity: 1 },
      { id: 'A5-5', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'A5-6', abbreviation: 'geum tang', decodedSpeciesId: 'geum', confidence: 'high', quantity: 3 },
      { id: 'A5-7', abbreviation: 'liatris ligul', decodedSpeciesId: 'liatris-ligulistylis', confidence: 'high', quantity: 2 },
      { id: 'A5-8', abbreviation: 'liatris spic', decodedSpeciesId: 'liatris', confidence: 'high', quantity: 1 },
      { id: 'A5-9', abbreviation: '*rattle-snak', decodedSpeciesId: 'rattlesnake-master', confidence: 'high', quantity: 1 },
      { id: 'A5-10', abbreviation: '*stipa barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 0, col: 5, id: 'A6',
    plantings: [
      { id: 'A6-1', abbreviation: 'verbena b', decodedSpeciesId: 'verbena-bonariensis', confidence: 'high', quantity: 4 },
      { id: 'A6-2', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 4 },
      { id: 'A6-3', abbreviation: 'baltic parsley', decodedSpeciesId: 'baltic-parsley', confidence: 'medium', quantity: 2 },
      { id: 'A6-4', abbreviation: 'liatris ligul', decodedSpeciesId: 'liatris-ligulistylis', confidence: 'high', quantity: 1 },
      { id: 'A6-5', abbreviation: 'knautia macedor', decodedSpeciesId: 'knautia-macedo', confidence: 'high', quantity: 3 },
      { id: 'A6-6', abbreviation: 'ceph gig', decodedSpeciesId: 'cephalaria-gigantea', confidence: 'high', quantity: 1 },
      { id: 'A6-7', abbreviation: 'salvia NC', decodedSpeciesId: 'nepeta', confidence: 'medium', quantity: 2 },
      { id: 'A6-8', abbreviation: 'sea holly', decodedSpeciesId: 'sea-holly', confidence: 'high', quantity: 2 },
      { id: 'A6-9', abbreviation: 'verbena hastata', decodedSpeciesId: 'verbena-hastata', confidence: 'high', quantity: 1 },
      { id: 'A6-10', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 3 },
    ],
    structures: [],
  },
  {
    row: 0, col: 6, id: 'A7',
    plantings: [],
    structures: [],
  },
  {
    row: 0, col: 7, id: 'A8',
    plantings: [],
    structures: [],
  },
  {
    row: 0, col: 8, id: 'A9',
    plantings: [
      { id: 'A9-1', abbreviation: 'cherry', decodedSpeciesId: 'cherry', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 0, col: 9, id: 'A10',
    plantings: [],
    structures: [],
  },

  // === ROW B ===
  {
    row: 1, col: 0, id: 'B1',
    plantings: [],
    structures: ['planter'],
  },
  {
    row: 1, col: 1, id: 'B2',
    plantings: [],
    structures: ['planter'],
  },
  {
    row: 1, col: 2, id: 'B3',
    plantings: [],
    structures: ['planter'],
  },
  {
    row: 1, col: 3, id: 'B4',
    plantings: [],
    structures: ['planter'],
  },
  {
    row: 1, col: 4, id: 'B5',
    plantings: [
      { id: 'B5-1', abbreviation: '*stipa barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'high', quantity: 4 },
      { id: 'B5-2', abbreviation: 'liatris spic', decodedSpeciesId: 'liatris', confidence: 'high', quantity: 2 },
      { id: 'B5-3', abbreviation: 'ECH. PV', decodedSpeciesId: 'echinacea-purpurea-vintage-wine', confidence: 'high', quantity: 3 },
      { id: 'B5-4', abbreviation: 'salv. LSp', decodedSpeciesId: 'little-spire', confidence: 'high', quantity: 3 },
      { id: 'B5-5', abbreviation: '*rattle snake', decodedSpeciesId: 'rattlesnake-master', confidence: 'high', quantity: 1 },
      { id: 'B5-6', abbreviation: 'baltp parsley', decodedSpeciesId: 'baltic-parsley', confidence: 'high', quantity: 1 },
      { id: 'B5-7', abbreviation: 'ECH PA', decodedSpeciesId: 'echinacea-pallida', confidence: 'high', quantity: 1 },
      { id: 'B5-8', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 1 },
      { id: 'B5-9', abbreviation: 'knautia macedo', decodedSpeciesId: 'knautia-macedo', confidence: 'high', quantity: 1 },
      { id: 'B5-10', abbreviation: 'rudbeck sub', decodedSpeciesId: 'rudbeckia', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 1, col: 5, id: 'B6',
    plantings: [
      { id: 'B6-1', abbreviation: 'STPG', decodedSpeciesId: 'stipa-tenuissima', confidence: 'high', quantity: 1 },
      { id: 'B6-2', abbreviation: 'salvia NC', decodedSpeciesId: 'nepeta', confidence: 'medium', quantity: 1 },
      { id: 'B6-3', abbreviation: 'verbena hastata', decodedSpeciesId: 'verbena-hastata', confidence: 'high', quantity: 1 },
      { id: 'B6-4', abbreviation: 'baltic parsley', decodedSpeciesId: 'baltic-parsley', confidence: 'medium', quantity: 3 },
      { id: 'B6-5', abbreviation: 'sprinter BX', decodedSpeciesId: 'sprinter-bx', confidence: 'high', quantity: 1 },
      { id: 'B6-6', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
      { id: 'B6-7', abbreviation: 'echinops exaltus', decodedSpeciesId: 'echinops-exaltus', confidence: 'high', quantity: 3 },
      { id: 'B6-8', abbreviation: 'ceph gig', decodedSpeciesId: 'cephalaria-gigantea', confidence: 'high', quantity: 2 },
      { id: 'B6-9', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 2 },
      { id: 'B6-10', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 1 },
      { id: 'B6-11', abbreviation: 'ECH PA', decodedSpeciesId: 'echinacea-pallida', confidence: 'high', quantity: 2 },
      { id: 'B6-12', abbreviation: 'sea holly', decodedSpeciesId: 'sea-holly', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 1, col: 6, id: 'B7',
    plantings: [
      { id: 'B7-1', abbreviation: 'baltic parsley', decodedSpeciesId: 'baltic-parsley', confidence: 'medium', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 1, col: 7, id: 'B8',
    plantings: [
      { id: 'B8-1', abbreviation: 'PHLX. PAND', decodedSpeciesId: 'phlox-paniculata-david', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 1, col: 8, id: 'B9',
    plantings: [],
    structures: [],
  },
  {
    row: 1, col: 9, id: 'B10',
    plantings: [],
    structures: [],
  },

  // === ROW C ===
  {
    row: 2, col: 0, id: 'C1',
    plantings: [],
    structures: ['planter'],
  },
  {
    row: 2, col: 1, id: 'C2',
    plantings: [],
    structures: ['planter'],
  },
  {
    row: 2, col: 2, id: 'C3',
    plantings: [
      { id: 'C3-1', abbreviation: '*stipa barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'high', quantity: 1 },
      { id: 'C3-2', abbreviation: 'veronica LAV', decodedSpeciesId: 'veronica-lav', confidence: 'high', quantity: 1 },
      { id: 'C3-3', abbreviation: 'ECH PA', decodedSpeciesId: 'echinacea-pallida', confidence: 'high', quantity: 1 },
    ],
    structures: ['planter'],
  },
  {
    row: 2, col: 3, id: 'C4',
    plantings: [
      { id: 'C4-1', abbreviation: 'ECH PA', decodedSpeciesId: 'echinacea-pallida', confidence: 'high', quantity: 4 },
      { id: 'C4-2', abbreviation: 'veronica LAV', decodedSpeciesId: 'veronica-lav', confidence: 'high', quantity: 1 },
      { id: 'C4-3', abbreviation: 'KF', decodedSpeciesId: 'karl-foerster', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 2, col: 4, id: 'C5',
    plantings: [
      { id: 'C5-1', abbreviation: 'ECH PA', decodedSpeciesId: 'echinacea-pallida', confidence: 'high', quantity: 5 },
      { id: 'C5-2', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 4 },
      { id: 'C5-3', abbreviation: 'ECH. PV', decodedSpeciesId: 'echinacea-purpurea-vintage-wine', confidence: 'high', quantity: 1 },
      { id: 'C5-4', abbreviation: 'menzies burnet', decodedSpeciesId: 'menzies-burnet', confidence: 'medium', quantity: 1 },
      { id: 'C5-5', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 2 },
      { id: 'C5-6', abbreviation: 'sang burn', decodedSpeciesId: 'sang-burn', confidence: 'medium', quantity: 1 },
      { id: 'C5-7', abbreviation: 'knautla macedon', decodedSpeciesId: 'knautia-macedo', confidence: 'high', quantity: 1 },
      { id: 'C5-8', abbreviation: 'rudbeck sub', decodedSpeciesId: 'rudbeckia', confidence: 'high', quantity: 2 },
      { id: 'C5-9', abbreviation: 'salvia NC', decodedSpeciesId: 'nepeta', confidence: 'medium', quantity: 1 },
      { id: 'C5-10', abbreviation: 'g. yellow hyssop', decodedSpeciesId: 'hyssop', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 2, col: 5, id: 'C6',
    plantings: [
      { id: 'C6-1', abbreviation: 'ceph gig', decodedSpeciesId: 'cephalaria-gigantea', confidence: 'high', quantity: 1 },
      { id: 'C6-2', abbreviation: 'STP.G', decodedSpeciesId: 'stipa-tenuissima', confidence: 'high', quantity: 1 },
      { id: 'C6-3', abbreviation: 'VERB. OLYM', decodedSpeciesId: 'verbascum-olympicum', confidence: 'high', quantity: 1 },
      { id: 'C6-4', abbreviation: 'veronica Red Arrow', decodedSpeciesId: 'veronica-red-arrow', confidence: 'high', quantity: 2 },
      { id: 'C6-5', abbreviation: 'sea holly', decodedSpeciesId: 'sea-holly', confidence: 'high', quantity: 1 },
      { id: 'C6-6', abbreviation: 'monarda b', decodedSpeciesId: 'monarda-bradburiana', confidence: 'high', quantity: 3 },
      { id: 'C6-7', abbreviation: 'little blue-stem', decodedSpeciesId: 'little-bluestem', confidence: 'medium', quantity: 2 },
      { id: 'C6-8', abbreviation: 'meadow rue', decodedSpeciesId: 'meadow-rue', confidence: 'high', quantity: 2 },
      { id: 'C6-9', abbreviation: 'VV', decodedSpeciesId: 'vernonia', confidence: 'medium', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 2, col: 6, id: 'C7',
    plantings: [
      { id: 'C7-1', abbreviation: 'Rs', decodedSpeciesId: 'russian-sage', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 2, col: 7, id: 'C8',
    plantings: [],
    structures: [],
  },
  {
    row: 2, col: 8, id: 'C9',
    plantings: [],
    structures: [],
  },
  {
    row: 2, col: 9, id: 'C10',
    plantings: [],
    structures: ['basement-stairs'],
  },

  // === ROW D ===
  {
    row: 3, col: 0, id: 'D1',
    plantings: [
      { id: 'D1-1', abbreviation: 'li-atris spic', decodedSpeciesId: 'liatris', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 3, col: 1, id: 'D2',
    plantings: [
      { id: 'D2-1', abbreviation: 'ECHPU', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 5 },
      { id: 'D2-2', abbreviation: 'lavender', decodedSpeciesId: 'lavender', confidence: 'high', quantity: 1 },
      { id: 'D2-3', abbreviation: 'sprinter BX', decodedSpeciesId: 'sprinter-bx', confidence: 'high', quantity: 1 },
      { id: 'D2-4', abbreviation: 'Verbas-NIgrum', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 2 },
      { id: 'D2-5', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'D2-6', abbreviation: 'liatris spic', decodedSpeciesId: 'liatris', confidence: 'high', quantity: 2 },
      { id: 'D2-7', abbreviation: '*rattle-snake', decodedSpeciesId: 'rattlesnake-master', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 3, col: 2, id: 'D3',
    plantings: [
      { id: 'D3-1', abbreviation: 'wood sp', decodedSpeciesId: 'wood-spurge', confidence: 'medium', quantity: 2 },
      { id: 'D3-2', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'D3-3', abbreviation: 'thyme', decodedSpeciesId: 'thyme', confidence: 'high', quantity: 1 },
      { id: 'D3-4', abbreviation: 'russian sage', decodedSpeciesId: 'russian-sage', confidence: 'high', quantity: 1 },
      { id: 'D3-5', abbreviation: 'ERYN BOU', decodedSpeciesId: 'eryngium-bourgatii', confidence: 'medium', quantity: 2 },
      { id: 'D3-6', abbreviation: 'Verbas-NIgrum', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 2 },
      { id: 'D3-7', abbreviation: 'fennel', decodedSpeciesId: 'fennel', confidence: 'high', quantity: 1 },
      { id: 'D3-8', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 1 },
      { id: 'D3-9', abbreviation: 'BAP.AUS', decodedSpeciesId: 'baptisia-australis', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 3, col: 3, id: 'D4',
    plantings: [
      { id: 'D4-1', abbreviation: 'YRW', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'D4-2', abbreviation: 'monarda b', decodedSpeciesId: 'monarda-bradburiana', confidence: 'high', quantity: 3 },
      { id: 'D4-3', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 4 },
      { id: 'D4-4', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
      { id: 'D4-5', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'D4-6', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 2 },
      { id: 'D4-7', abbreviation: 'salvia NC', decodedSpeciesId: 'nepeta', confidence: 'medium', quantity: 1 },
      { id: 'D4-8', abbreviation: 'salvia NEM...', decodedSpeciesId: 'salvia-nemorosa', confidence: 'high', quantity: 1 },
      { id: 'D4-9', abbreviation: 'salvia C', decodedSpeciesId: 'salvia', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 3, col: 4, id: 'D5',
    plantings: [
      { id: 'D5-1', abbreviation: 'PHLX. PAN. Jeana', decodedSpeciesId: 'phlox-paniculata-jeana', confidence: 'medium', quantity: 1 },
      { id: 'D5-2', abbreviation: 'meadowrue', decodedSpeciesId: 'meadow-rue', confidence: 'high', quantity: 1 },
      { id: 'D5-3', abbreviation: 'little blue-stem', decodedSpeciesId: 'little-bluestem', confidence: 'medium', quantity: 3 },
      { id: 'D5-4', abbreviation: 'VERB. OLYM', decodedSpeciesId: 'verbascum-olympicum', confidence: 'high', quantity: 1 },
      { id: 'D5-5', abbreviation: 'STPO', decodedSpeciesId: 'stipa-barbata', confidence: 'low', quantity: 1 },
      { id: 'D5-6', abbreviation: 'salvia NC', decodedSpeciesId: 'nepeta', confidence: 'medium', quantity: 1 },
      { id: 'D5-7', abbreviation: 'aster SYM LAE', decodedSpeciesId: 'aster-sym-lae', confidence: 'medium', quantity: 2 },
      { id: 'D5-8', abbreviation: 'salvia NEM.C', decodedSpeciesId: 'salvia', confidence: 'high', quantity: 1 },
      { id: 'D5-9', abbreviation: 'JPY', decodedSpeciesId: 'phlox-paniculata-jeana', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 3, col: 5, id: 'D6',
    plantings: [
      { id: 'D6-1', abbreviation: 'meadow rue', decodedSpeciesId: 'meadow-rue', confidence: 'high', quantity: 1 },
      { id: 'D6-2', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
      { id: 'D6-3', abbreviation: 'monarda b', decodedSpeciesId: 'monarda-bradburiana', confidence: 'high', quantity: 1 },
      { id: 'D6-4', abbreviation: 'little blue-stem', decodedSpeciesId: 'little-bluestem', confidence: 'medium', quantity: 3 },
      { id: 'D6-5', abbreviation: 'russian sage', decodedSpeciesId: 'russian-sage', confidence: 'high', quantity: 1 },
      { id: 'D6-6', abbreviation: 'sprinter BX', decodedSpeciesId: 'sprinter-bx', confidence: 'high', quantity: 1 },
      { id: 'D6-7', abbreviation: 'thyme', decodedSpeciesId: 'thyme', confidence: 'high', quantity: 2 },
      { id: 'D6-8', abbreviation: 'STP G', decodedSpeciesId: 'stipa-tenuissima', confidence: 'high', quantity: 1 },
      { id: 'D6-9', abbreviation: 'veronica Red Arrow', decodedSpeciesId: 'veronica-red-arrow', confidence: 'high', quantity: 1 },
      { id: 'D6-10', abbreviation: 'ceph gig', decodedSpeciesId: 'cephalaria-gigantea', confidence: 'high', quantity: 1 },
      { id: 'D6-11', abbreviation: 'VERB. OLYM', decodedSpeciesId: 'verbascum-olympicum', confidence: 'high', quantity: 1 },
      { id: 'D6-12', abbreviation: 'UPYW', decodedSpeciesId: 'phlox-paniculata-jeana', confidence: 'low', quantity: 1 },
      { id: 'D6-13', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 3, col: 6, id: 'D7',
    plantings: [
      { id: 'D7-1', abbreviation: 'phlox', decodedSpeciesId: 'phlox', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 3, col: 7, id: 'D8',
    plantings: [],
    structures: [],
  },
  {
    row: 3, col: 8, id: 'D9',
    plantings: [],
    structures: [],
  },
  {
    row: 3, col: 9, id: 'D10',
    plantings: [],
    structures: ['barbecue'],
  },

  // === ROW E ===
  {
    row: 4, col: 0, id: 'E1',
    plantings: [
      { id: 'E1-1', abbreviation: 'sprinter BX', decodedSpeciesId: 'sprinter-bx', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 4, col: 1, id: 'E2',
    plantings: [
      { id: 'E2-1', abbreviation: 'ECHPU', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 2 },
      { id: 'E2-2', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'E2-3', abbreviation: 'ACI', decodedSpeciesId: 'actaea-chocoholic', confidence: 'low', quantity: 1 },
      { id: 'E2-4', abbreviation: 'liatris spic', decodedSpeciesId: 'liatris', confidence: 'high', quantity: 1 },
      { id: 'E2-5', abbreviation: 'foxtail lily', decodedSpeciesId: 'foxtail-lily', confidence: 'medium', quantity: 1 },
      { id: 'E2-6', abbreviation: 'Verbas-Nigrum', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 2 },
      { id: 'E2-7', abbreviation: 'achillea', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'E2-8', abbreviation: 'SA gras', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 2 },
      { id: 'E2-9', abbreviation: 'echinops', decodedSpeciesId: 'echinops', confidence: 'high', quantity: 1 },
      { id: 'E2-10', abbreviation: 'rattle-master', decodedSpeciesId: 'rattlesnake-master', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 4, col: 2, id: 'E3',
    plantings: [
      { id: 'E3-1', abbreviation: 'fennel', decodedSpeciesId: 'fennel', confidence: 'high', quantity: 2 },
      { id: 'E3-2', abbreviation: 'foxtail lily', decodedSpeciesId: 'foxtail-lily', confidence: 'medium', quantity: 1 },
      { id: 'E3-3', abbreviation: 'liatris ligul', decodedSpeciesId: 'liatris-ligulistylis', confidence: 'high', quantity: 2 },
      { id: 'E3-4', abbreviation: 'Verbas-NIgrum', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 4 },
      { id: 'E3-5', abbreviation: 'paniculum cloud nine', decodedSpeciesId: 'panicum-cloud-nine', confidence: 'high', quantity: 2 },
      { id: 'E3-6', abbreviation: 'veronica Red Arrow', decodedSpeciesId: 'veronica-red-arrow', confidence: 'high', quantity: 1 },
      { id: 'E3-7', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 1 },
      { id: 'E3-8', abbreviation: 'verbasc. olympic', decodedSpeciesId: 'verbascum-olympicum', confidence: 'high', quantity: 1 },
      { id: 'E3-9', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'E3-10', abbreviation: 'russian sage', decodedSpeciesId: 'russian-sage', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 4, col: 3, id: 'E4',
    plantings: [
      { id: 'E4-1', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 1 },
      { id: 'E4-2', abbreviation: 'SA sungras', decodedSpeciesId: 'salvia', confidence: 'low', quantity: 1 },
      { id: 'E4-3', abbreviation: 'PVG*', decodedSpeciesId: 'panicum-virgatum', confidence: 'high', quantity: 1 },
      { id: 'E4-4', abbreviation: 'WH', decodedSpeciesId: 'muhlenbergia-white-cloud', confidence: 'medium', quantity: 1 },
      { id: 'E4-5', abbreviation: 'Viburnum x bodnantense \'Dawn\'', decodedSpeciesId: 'viburnum', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 4, col: 4, id: 'E5',
    plantings: [
      { id: 'E5-1', abbreviation: 'aster SYM LAE', decodedSpeciesId: 'aster-sym-lae', confidence: 'medium', quantity: 1 },
      { id: 'E5-2', abbreviation: 'golden rod', decodedSpeciesId: 'golden-rod', confidence: 'high', quantity: 3 },
      { id: 'E5-3', abbreviation: 'little blue-stem', decodedSpeciesId: 'little-bluestem', confidence: 'medium', quantity: 2 },
      { id: 'E5-4', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'E5-5', abbreviation: 'EchPV', decodedSpeciesId: 'echinacea-purpurea-vintage-wine', confidence: 'high', quantity: 3 },
      { id: 'E5-6', abbreviation: 'russian sage', decodedSpeciesId: 'russian-sage', confidence: 'high', quantity: 1 },
      { id: 'E5-7', abbreviation: 'STP.G', decodedSpeciesId: 'stipa-tenuissima', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 4, col: 5, id: 'E6',
    plantings: [
      { id: 'E6-1', abbreviation: 'JPYW', decodedSpeciesId: 'joe-pye-weed', confidence: 'medium', quantity: 2 },
      { id: 'E6-2', abbreviation: 'sang blk', decodedSpeciesId: 'sanguisorba', confidence: 'medium', quantity: 2 },
      { id: 'E6-3', abbreviation: 'VERB. OLYM.', decodedSpeciesId: 'verbascum-olympicum', confidence: 'high', quantity: 1 },
      { id: 'E6-4', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 1 },
      { id: 'E6-5', abbreviation: 'PHL. TUBA', decodedSpeciesId: 'phlox-tuba', confidence: 'medium', quantity: 1 },
      { id: 'E6-6', abbreviation: 'salvia NC', decodedSpeciesId: 'nepeta', confidence: 'medium', quantity: 1 },
      { id: 'E6-7', abbreviation: 'sprob hetero', decodedSpeciesId: 'sporobolus-heterolepis', confidence: 'high', quantity: 1 },
      { id: 'E6-8', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 3 },
    ],
    structures: [],
  },
  {
    row: 4, col: 6, id: 'E7',
    plantings: [
      { id: 'E7-1', abbreviation: 'PHL. TUBA', decodedSpeciesId: 'phlox-tuba', confidence: 'medium', quantity: 1 },
      { id: 'E7-2', abbreviation: 'JSBF', decodedSpeciesId: 'joe-pye-weed', confidence: 'medium', quantity: 2 },
      { id: 'E7-3', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 1 },
      { id: 'E7-4', abbreviation: 'EchGJ', decodedSpeciesId: 'echinacea-green-jewel', confidence: 'medium', quantity: 2 },
      { id: 'E7-5', abbreviation: 'sprob hetero', decodedSpeciesId: 'sporobolus-heterolepis', confidence: 'high', quantity: 1 },
      { id: 'E7-6', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 3 },
      { id: 'E7-7', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 4, col: 7, id: 'E8',
    plantings: [
      { id: 'E8-1', abbreviation: 'verbas-cum nlgrum alba', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 2 },
      { id: 'E8-2', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 2 },
      { id: 'E8-3', abbreviation: 'aruncus horatio', decodedSpeciesId: 'aruncus-horatia', confidence: 'high', quantity: 2 },
      { id: 'E8-4', abbreviation: 'EchGo', decodedSpeciesId: 'echinacea-green-jewel', confidence: 'medium', quantity: 1 },
      { id: 'E8-5', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 3 },
    ],
    structures: [],
  },
  {
    row: 4, col: 8, id: 'E9',
    plantings: [],
    structures: [],
  },
  {
    row: 4, col: 9, id: 'E10',
    plantings: [],
    structures: ['barbecue'],
  },

  // === ROW F ===
  {
    row: 5, col: 0, id: 'F1',
    plantings: [
      { id: 'F1-1', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 7 },
      { id: 'F1-2', abbreviation: 'verbena b', decodedSpeciesId: 'verbena-bonariensis', confidence: 'high', quantity: 1 },
      { id: 'F1-3', abbreviation: 'nepeta', decodedSpeciesId: 'nepeta', confidence: 'high', quantity: 1 },
      { id: 'F1-4', abbreviation: 'echinops', decodedSpeciesId: 'echinops', confidence: 'high', quantity: 1 },
      { id: 'F1-5', abbreviation: 'salvia nem', decodedSpeciesId: 'salvia-nemorosa', confidence: 'high', quantity: 3 },
    ],
    structures: [],
  },
  {
    row: 5, col: 1, id: 'F2',
    plantings: [
      { id: 'F2-1', abbreviation: 'nepeta', decodedSpeciesId: 'nepeta', confidence: 'high', quantity: 2 },
      { id: 'F2-2', abbreviation: 'rudbekia sub', decodedSpeciesId: 'rudbeckia', confidence: 'high', quantity: 1 },
      { id: 'F2-3', abbreviation: 'SB', decodedSpeciesId: 'salvia', confidence: 'medium', quantity: 1 },
      { id: 'F2-4', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 5, col: 2, id: 'F3',
    plantings: [
      { id: 'F3-1', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 2 },
      { id: 'F3-2', abbreviation: 'PhR', decodedSpeciesId: 'pennisetum', confidence: 'medium', quantity: 4 },
      { id: 'F3-3', abbreviation: 'veronica Red Arrow', decodedSpeciesId: 'veronica-red-arrow', confidence: 'high', quantity: 1 },
      { id: 'F3-4', abbreviation: 'Verbas-Nigrum', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 1 },
      { id: 'F3-5', abbreviation: 'persicaria polymorpha', decodedSpeciesId: 'persicaria-polymorpha', confidence: 'high', quantity: 1 },
      { id: 'F3-6', abbreviation: 'VV', decodedSpeciesId: 'vernonia', confidence: 'medium', quantity: 2 },
      { id: 'F3-7', abbreviation: 'echinops', decodedSpeciesId: 'echinops', confidence: 'high', quantity: 1 },
      { id: 'F3-8', abbreviation: 'monarda brad', decodedSpeciesId: 'monarda', confidence: 'high', quantity: 3 },
    ],
    structures: [],
  },
  {
    row: 5, col: 3, id: 'F4',
    plantings: [
      { id: 'F4-1', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
      { id: 'F4-2', abbreviation: 'aster.FM', decodedSpeciesId: 'aster-fm', confidence: 'medium', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 5, col: 4, id: 'F5',
    plantings: [
      { id: 'F5-1', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
      { id: 'F5-2', abbreviation: 'ACh', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'F5-3', abbreviation: 'russian sage', decodedSpeciesId: 'russian-sage', confidence: 'high', quantity: 1 },
      { id: 'F5-4', abbreviation: 'JPYW', decodedSpeciesId: 'joe-pye-weed', confidence: 'medium', quantity: 1 },
      { id: 'F5-5', abbreviation: 'san-gulsorba squrrel', decodedSpeciesId: 'san-guisorba-squirrel', confidence: 'medium', quantity: 2 },
      { id: 'F5-6', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 2 },
      { id: 'F5-7', abbreviation: 'PVG', decodedSpeciesId: 'panicum-virgatum', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 5, col: 5, id: 'F6',
    plantings: [
      { id: 'F6-1', abbreviation: 'YW', decodedSpeciesId: 'yarrow', confidence: 'low', quantity: 1 },
      { id: 'F6-2', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'F6-3', abbreviation: 'Veron Fasc', decodedSpeciesId: 'veronica-fascination', confidence: 'high', quantity: 1 },
      { id: 'F6-4', abbreviation: 'PVG', decodedSpeciesId: 'panicum-virgatum', confidence: 'high', quantity: 2 },
      { id: 'F6-5', abbreviation: 'swamp milkweed', decodedSpeciesId: 'swamp-milkweed', confidence: 'high', quantity: 1 },
      { id: 'F6-6', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
      { id: 'F6-7', abbreviation: 'ceph gig', decodedSpeciesId: 'cephalaria-gigantea', confidence: 'high', quantity: 1 },
      { id: 'F6-8', abbreviation: 'sprob hetero', decodedSpeciesId: 'sporobolus-heterolepis', confidence: 'high', quantity: 1 },
      { id: 'F6-9', abbreviation: 'salvia NC', decodedSpeciesId: 'nepeta', confidence: 'medium', quantity: 1 },
      { id: 'F6-10', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 5, col: 6, id: 'F7',
    plantings: [
      { id: 'F7-1', abbreviation: 'salvia NC', decodedSpeciesId: 'nepeta', confidence: 'medium', quantity: 2 },
      { id: 'F7-2', abbreviation: 'sprob hetero', decodedSpeciesId: 'sporobolus-heterolepis', confidence: 'high', quantity: 1 },
      { id: 'F7-3', abbreviation: 'PHLX. PAND', decodedSpeciesId: 'phlox-paniculata-david', confidence: 'high', quantity: 1 },
      { id: 'F7-4', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
      { id: 'F7-5', abbreviation: 'PVG', decodedSpeciesId: 'panicum-virgatum', confidence: 'high', quantity: 2 },
      { id: 'F7-6', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'F7-7', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'F7-8', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'F7-9', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 5, col: 7, id: 'F8',
    plantings: [
      { id: 'F8-1', abbreviation: 'PHLX. PAND', decodedSpeciesId: 'phlox-paniculata-david', confidence: 'high', quantity: 1 },
      { id: 'F8-2', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'F8-3', abbreviation: 'aruncus horatio', decodedSpeciesId: 'aruncus-horatia', confidence: 'high', quantity: 1 },
      { id: 'F8-4', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'F8-5', abbreviation: 'STP.G', decodedSpeciesId: 'stipa-tenuissima', confidence: 'high', quantity: 1 },
      { id: 'F8-6', abbreviation: 'sprob hetero', decodedSpeciesId: 'sporobolus-heterolepis', confidence: 'high', quantity: 1 },
      { id: 'F8-7', abbreviation: 'sprob hetero', decodedSpeciesId: 'sporobolus-heterolepis', confidence: 'high', quantity: 1 },
      { id: 'F8-8', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 5, col: 8, id: 'F9',
    plantings: [
      { id: 'F9-1', abbreviation: 'little spire', decodedSpeciesId: 'little-spire', confidence: 'medium', quantity: 1 },
      { id: 'F9-2', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 1 },
      { id: 'F9-3', abbreviation: 'agastache blue fortune', decodedSpeciesId: 'eupatorium-blue-fortune', confidence: 'medium', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 5, col: 9, id: 'F10',
    plantings: [],
    structures: [],
  },

  // === ROW G ===
  {
    row: 6, col: 0, id: 'G1',
    plantings: [
      { id: 'G1-1', abbreviation: 'echinops', decodedSpeciesId: 'echinops', confidence: 'high', quantity: 1 },
      { id: 'G1-2', abbreviation: 'salvia nem', decodedSpeciesId: 'salvia-nemorosa', confidence: 'high', quantity: 2 },
      { id: 'G1-3', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'G1-4', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 5 },
      { id: 'G1-5', abbreviation: 'verbena b', decodedSpeciesId: 'verbena-bonariensis', confidence: 'high', quantity: 1 },
      { id: 'G1-6', abbreviation: '*stipa barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'high', quantity: 3 },
    ],
    structures: [],
  },
  {
    row: 6, col: 1, id: 'G2',
    plantings: [
      { id: 'G2-1', abbreviation: 'rudbekia sub', decodedSpeciesId: 'rudbeckia', confidence: 'high', quantity: 1 },
      { id: 'G2-2', abbreviation: '*stipa barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'high', quantity: 1 },
      { id: 'G2-3', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 2 },
      { id: 'G2-4', abbreviation: 'W/H', decodedSpeciesId: 'winterberry-holly', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 6, col: 2, id: 'G3',
    plantings: [
      { id: 'G3-1', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 2 },
      { id: 'G3-2', abbreviation: 'aster.FM', decodedSpeciesId: 'aster-fm', confidence: 'medium', quantity: 1 },
      { id: 'G3-3', abbreviation: 'KF', decodedSpeciesId: 'karl-foerster', confidence: 'high', quantity: 2 },
      { id: 'G3-4', abbreviation: 'poppy', decodedSpeciesId: 'poppy', confidence: 'high', quantity: 1 },
      { id: 'G3-5', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 6, col: 3, id: 'G4',
    plantings: [
      { id: 'G4-1', abbreviation: 'aster.FM', decodedSpeciesId: 'aster-fm', confidence: 'medium', quantity: 2 },
      { id: 'G4-2', abbreviation: 'persicaria polymorpha', decodedSpeciesId: 'persicaria-polymorpha', confidence: 'high', quantity: 1 },
      { id: 'G4-3', abbreviation: 'verbena hastata', decodedSpeciesId: 'verbena-hastata', confidence: 'high', quantity: 3 },
      { id: 'G4-4', abbreviation: 'YRW', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
      { id: 'G4-5', abbreviation: 'milkweed', decodedSpeciesId: 'swamp-milkweed', confidence: 'medium', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 6, col: 4, id: 'G5',
    plantings: [
      { id: 'G5-1', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 2 },
      { id: 'G5-2', abbreviation: 'PVG', decodedSpeciesId: 'panicum-virgatum', confidence: 'high', quantity: 3 },
      { id: 'G5-3', abbreviation: 'baltic parsley', decodedSpeciesId: 'baltic-parsley', confidence: 'medium', quantity: 1 },
      { id: 'G5-4', abbreviation: 'Verbas-Nigrum', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 1 },
      { id: 'G5-5', abbreviation: 'golden rod', decodedSpeciesId: 'golden-rod', confidence: 'high', quantity: 2 },
      { id: 'G5-6', abbreviation: 'milkweed', decodedSpeciesId: 'swamp-milkweed', confidence: 'medium', quantity: 5 },
      { id: 'G5-7', abbreviation: 'sneeze weed', decodedSpeciesId: 'helenium', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 6, col: 5, id: 'G6',
    plantings: [
      { id: 'G6-1', abbreviation: 'PVG', decodedSpeciesId: 'panicum-virgatum', confidence: 'high', quantity: 1 },
      { id: 'G6-2', abbreviation: 'swamp milkweed', decodedSpeciesId: 'swamp-milkweed', confidence: 'high', quantity: 2 },
      { id: 'G6-3', abbreviation: 'golden rod', decodedSpeciesId: 'golden-rod', confidence: 'high', quantity: 4 },
      { id: 'G6-4', abbreviation: 'red twig dogwood', decodedSpeciesId: 'red-twig-dogwood', confidence: 'high', quantity: 1 },
      { id: 'G6-5', abbreviation: 'knautia maced', decodedSpeciesId: 'knautia-macedo', confidence: 'high', quantity: 4 },
      { id: 'G6-6', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 6, col: 6, id: 'G7',
    plantings: [
      { id: 'G7-1', abbreviation: 'PVG', decodedSpeciesId: 'panicum-virgatum', confidence: 'high', quantity: 2 },
      { id: 'G7-2', abbreviation: 'kniphofia uvalia', decodedSpeciesId: 'kniphofia-uvaria', confidence: 'medium', quantity: 1 },
      { id: 'G7-3', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 15 },
      { id: 'G7-4', abbreviation: 'LBC', decodedSpeciesId: 'little-bluestem', confidence: 'medium', quantity: 3 },
      { id: 'G7-5', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
    ],
    structures: [],
  },
  {
    row: 6, col: 7, id: 'G8',
    plantings: [
      { id: 'G8-1', abbreviation: 'LBC', decodedSpeciesId: 'little-bluestem', confidence: 'medium', quantity: 4 },
      { id: 'G8-2', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'G8-3', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'G8-4', abbreviation: 'hosta halcyon', decodedSpeciesId: 'hosta-halcyon', confidence: 'high', quantity: 1 },
      { id: 'G8-5', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 2 },
      { id: 'G8-6', abbreviation: 'sprob hetero', decodedSpeciesId: 'sporobolus-heterolepis', confidence: 'high', quantity: 1 },
      { id: 'G8-7', abbreviation: 'little spire', decodedSpeciesId: 'little-spire', confidence: 'medium', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 6, col: 8, id: 'G9',
    plantings: [
      { id: 'G9-1', abbreviation: 'little spire', decodedSpeciesId: 'little-spire', confidence: 'medium', quantity: 2 },
      { id: 'G9-2', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 5 },
      { id: 'G9-3', abbreviation: 'chP', decodedSpeciesId: 'cherry', confidence: 'low', quantity: 2 },
      { id: 'G9-4', abbreviation: 'agastache blue fortune', decodedSpeciesId: 'eupatorium-blue-fortune', confidence: 'medium', quantity: 2 },
    ],
    structures: [],
  },
  {
    row: 6, col: 9, id: 'G10',
    plantings: [],
    structures: [],
  },

  // === ROW H ===
  {
    row: 7, col: 0, id: 'H1',
    plantings: [
      { id: 'H1-1', abbreviation: '*stipa barbata barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'medium', quantity: 1 },
      { id: 'H1-2', abbreviation: '*stipa barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'high', quantity: 1 },
      { id: 'H1-3', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 7, col: 1, id: 'H2',
    plantings: [],
    structures: [],
  },
  {
    row: 7, col: 2, id: 'H3',
    plantings: [
      { id: 'H3-1', abbreviation: 'paniculum cloud nine', decodedSpeciesId: 'panicum-cloud-nine', confidence: 'high', quantity: 2 },
      { id: 'H3-2', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'H3-3', abbreviation: 'PhR', decodedSpeciesId: 'pennisetum', confidence: 'medium', quantity: 1 },
      { id: 'H3-4', abbreviation: 'red twig dogwood', decodedSpeciesId: 'red-twig-dogwood', confidence: 'high', quantity: 1 },
      { id: 'H3-5', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 7, col: 3, id: 'H4',
    plantings: [
      { id: 'H4-1', abbreviation: 'salvia nem.c', decodedSpeciesId: 'salvia', confidence: 'high', quantity: 1 },
      { id: 'H4-2', abbreviation: 'YRW', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 3 },
      { id: 'H4-3', abbreviation: 'verbena hast', decodedSpeciesId: 'verbena-hastata', confidence: 'high', quantity: 2 },
      { id: 'H4-4', abbreviation: '*stipa barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'high', quantity: 3 },
      { id: 'H4-5', abbreviation: 'Verbas-NIgrum', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 1 },
      { id: 'H4-6', abbreviation: 'echinops', decodedSpeciesId: 'echinops', confidence: 'high', quantity: 1 },
      { id: 'H4-7', abbreviation: 'JSBF', decodedSpeciesId: 'joe-pye-weed', confidence: 'medium', quantity: 3 },
      { id: 'H4-8', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'H4-9', abbreviation: 'red twig dogwood', decodedSpeciesId: 'red-twig-dogwood', confidence: 'high', quantity: 1 },
      { id: 'H4-10', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 7, col: 4, id: 'H5',
    plantings: [
      { id: 'H5-1', abbreviation: 'sneeze weed', decodedSpeciesId: 'helenium', confidence: 'high', quantity: 5 },
      { id: 'H5-2', abbreviation: 'Verbas-Nigrum', decodedSpeciesId: 'verbascum-nigrum', confidence: 'medium', quantity: 1 },
      { id: 'H5-3', abbreviation: 'PVG', decodedSpeciesId: 'panicum-virgatum', confidence: 'high', quantity: 1 },
      { id: 'H5-4', abbreviation: 'Japan-FG', decodedSpeciesId: 'japanese-forest-grass', confidence: 'medium', quantity: 1 },
      { id: 'H5-5', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 2 },
    ],
    structures: [],
  },
  {
    row: 7, col: 5, id: 'H6',
    plantings: [
      { id: 'H6-1', abbreviation: 'panicum cloud nine', decodedSpeciesId: 'panicum-cloud-nine', confidence: 'high', quantity: 1 },
      { id: 'H6-2', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 3 },
      { id: 'H6-3', abbreviation: 'daylily', decodedSpeciesId: 'daylily', confidence: 'high', quantity: 1 },
      { id: 'H6-4', abbreviation: 'cinnamon fern', decodedSpeciesId: 'cinnamon-fern', confidence: 'high', quantity: 1 },
      { id: 'H6-5', abbreviation: 'sprinter BX', decodedSpeciesId: 'sprinter-bx', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 7, col: 6, id: 'H7',
    plantings: [
      { id: 'H7-1', abbreviation: 'hosta halcyon', decodedSpeciesId: 'hosta-halcyon', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 7, col: 7, id: 'H8',
    plantings: [
      { id: 'H8-1', abbreviation: 'EchP', decodedSpeciesId: 'echinacea-purpurea', confidence: 'high', quantity: 1 },
      { id: 'H8-2', abbreviation: 'panlculum cloud nlne', decodedSpeciesId: 'panicum-cloud-nine', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 7, col: 8, id: 'H9',
    plantings: [
      { id: 'H9-1', abbreviation: 'camellia snowman', decodedSpeciesId: 'camellia', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 7, col: 9, id: 'H10',
    plantings: [
      { id: 'H10-1', abbreviation: 'verbena b', decodedSpeciesId: 'verbena-bonariensis', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },

  // === ROW I ===
  {
    row: 8, col: 0, id: 'I1',
    plantings: [],
    structures: ['hot-tub'],
  },
  {
    row: 8, col: 1, id: 'I2',
    plantings: [],
    structures: [],
  },
  {
    row: 8, col: 2, id: 'I3',
    plantings: [
      { id: 'I3-1', abbreviation: 'PhR', decodedSpeciesId: 'pennisetum', confidence: 'medium', quantity: 3 },
      { id: 'I3-2', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 4 },
      { id: 'I3-3', abbreviation: 'ech pallida', decodedSpeciesId: 'echinacea-pallida', confidence: 'high', quantity: 4 },
      { id: 'I3-4', abbreviation: 'monarda brad', decodedSpeciesId: 'monarda', confidence: 'high', quantity: 1 },
      { id: 'I3-5', abbreviation: 'rudbekia lacinata', decodedSpeciesId: 'rudbeckia-laciniata', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 8, col: 3, id: 'I4',
    plantings: [
      { id: 'I4-1', abbreviation: 'YRW', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 2 },
      { id: 'I4-2', abbreviation: 'JSBF', decodedSpeciesId: 'joe-pye-weed', confidence: 'medium', quantity: 1 },
      { id: 'I4-3', abbreviation: 'stipa barbata', decodedSpeciesId: 'stipa-barbata', confidence: 'high', quantity: 1 },
      { id: 'I4-4', abbreviation: 'ACH', decodedSpeciesId: 'achillea', confidence: 'high', quantity: 2 },
      { id: 'I4-5', abbreviation: 'dogwood', decodedSpeciesId: 'red-twig-dogwood', confidence: 'medium', quantity: 1 },
      { id: 'I4-6', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
      { id: 'I4-7', abbreviation: 'monarda brad', decodedSpeciesId: 'monarda', confidence: 'high', quantity: 1 },
      { id: 'I4-8', abbreviation: 'SA gras', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 2 },
      { id: 'I4-9', abbreviation: 'aruncus horatio', decodedSpeciesId: 'aruncus-horatia', confidence: 'high', quantity: 2 },
    ],
    structures: [],
  },
  {
    row: 8, col: 4, id: 'I5',
    plantings: [
      { id: 'I5-1', abbreviation: 'daylily', decodedSpeciesId: 'daylily', confidence: 'high', quantity: 1 },
      { id: 'I5-2', abbreviation: 'aruncus horatio', decodedSpeciesId: 'aruncus-horatia', confidence: 'high', quantity: 2 },
    ],
    structures: [],
  },
  {
    row: 8, col: 5, id: 'I6',
    plantings: [
      { id: 'I6-1', abbreviation: 'daylily', decodedSpeciesId: 'daylily', confidence: 'high', quantity: 3 },
      { id: 'I6-2', abbreviation: 'aruncus horatio', decodedSpeciesId: 'aruncus-horatia', confidence: 'high', quantity: 2 },
      { id: 'I6-3', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 3 },
      { id: 'I6-4', abbreviation: 'cinnamon fern', decodedSpeciesId: 'cinnamon-fern', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 8, col: 6, id: 'I7',
    plantings: [
      { id: 'I7-1', abbreviation: 'cinnamon fern', decodedSpeciesId: 'cinnamon-fern', confidence: 'high', quantity: 3 },
      { id: 'I7-2', abbreviation: 'SA', decodedSpeciesId: 'salvia', confidence: 'high', quantity: 1 },
      { id: 'I7-3', abbreviation: 'unlabeled', decodedSpeciesId: 'unknown', confidence: 'low', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 8, col: 7, id: 'I8',
    plantings: [],
    structures: [],
  },
  {
    row: 8, col: 8, id: 'I9',
    plantings: [],
    structures: [],
  },
  {
    row: 8, col: 9, id: 'I10',
    plantings: [],
    structures: [],
  },

  // === ROW J ===
  {
    row: 9, col: 0, id: 'J1',
    plantings: [],
    structures: ['hot-tub'],
  },
  {
    row: 9, col: 1, id: 'J2',
    plantings: [],
    structures: [],
  },
  {
    row: 9, col: 2, id: 'J3',
    plantings: [
      { id: 'J3-1', abbreviation: 'rudbekia laciniata', decodedSpeciesId: 'rudbeckia-laciniata', confidence: 'high', quantity: 2 },
    ],
    structures: [],
  },
  {
    row: 9, col: 3, id: 'J4',
    plantings: [
      { id: 'J4-1', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 2 },
      { id: 'J4-2', abbreviation: 'aruncus horatio', decodedSpeciesId: 'aruncus-horatia', confidence: 'high', quantity: 2 },
      { id: 'J4-3', abbreviation: 'amaranth', decodedSpeciesId: 'amaranth', confidence: 'high', quantity: 6 },
    ],
    structures: [],
  },
  {
    row: 9, col: 4, id: 'J5',
    plantings: [
      { id: 'J5-1', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 9, col: 5, id: 'J6',
    plantings: [
      { id: 'J6-1', abbreviation: 'SA grass', decodedSpeciesId: 'sa-grass', confidence: 'medium', quantity: 1 },
      { id: 'J6-2', abbreviation: 'cinnamon fern', decodedSpeciesId: 'cinnamon-fern', confidence: 'high', quantity: 1 },
    ],
    structures: [],
  },
  {
    row: 9, col: 6, id: 'J7',
    plantings: [],
    structures: [],
  },
  {
    row: 9, col: 7, id: 'J8',
    plantings: [],
    structures: [],
  },
  {
    row: 9, col: 8, id: 'J9',
    plantings: [],
    structures: ['bench'],
  },
  {
    row: 9, col: 9, id: 'J10',
    plantings: [],
    structures: [],
  },
];

export const gridCellMap = new Map(gridAssignments.map(c => [c.id, c]));
